### ISSUE TITLE
popup problem for points

### ISSUE THREAD

**Issue by soli004** [Leaflet/Leaflet.VectorGrid#216] opened 2019-09-24 15:25 UTC
Hello,
Maybe someone here can give a hint what is the issue I'm having with the popup for the points. Asked in stackoverflow so link below. Thank you
[https://stackoverflow.com/questions/58072432/popup-window-for-points-using-leaflet-vectorgrid-error-lat-of-undefined](url)

**Comment by tomchadwin** [comment] 2019-09-24 15:54
Duplicate of #148

**Closed by tomchadwin** 2019-09-24 15:54 UTC
