### ISSUE TITLE
Polygon vector tile bounding line

### ISSUE THREAD

**Issue by wsf1990** [Leaflet/Leaflet.VectorGrid#209] opened 2019-07-07 05:37 UTC
Hi,
I use this package to load pbf vt tiles,which data's geom type is polygon.I found that when loading,It will show a line between tiles. So how to remove this bounding line? 
![image](https://user-images.githubusercontent.com/8774884/60764448-a4c23e80-a0bc-11e9-8f1e-c44868bcbbd7.png)

![image](https://user-images.githubusercontent.com/8774884/60765541-8d8c4c80-a0ce-11e9-9262-f8ef29143794.png)

**Comment by wsf1990** [comment] 2019-07-07 06:29
Maybe this is a issue of geoserver,Which I used to publish pbf vt.

**Comment by IvanSanchez** [comment] 2019-07-07 23:06
Duplicate of #120.

**Closed by IvanSanchez** 2019-07-07 23:06 UTC
