### ISSUE TITLE
Cannot get demo to work

### ISSUE THREAD

**Issue by mg262** [Leaflet/Leaflet.VectorGrid#34] opened 2016-11-22 14:54 UTC
I can't get http://leaflet.github.io/Leaflet.VectorGrid/dist/demo/demo-vectortiles.html to display anything on my local machine. I have followed the documentation to produce `dist/Leaflet.VectorGrid.bundled.js`. and made sure the html file has sensible paths to it and to the leaflet files, but only see 

![image](https://cloud.githubusercontent.com/assets/8794583/20528247/528e6bac-b0c3-11e6-83f0-f721940a724b.png)

I have tried the following, which do not resolve the problem

-- different browser (Chrome -> Firefox)
-- `unpkg` for the includes: 

	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css"/>
	<script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet-src.js"></script>
	<script src="https://unpkg.com/leaflet.vectorgrid@latest/dist/Leaflet.VectorGrid.bundled.js"></script>

-- substituting my own MapBox API token.

I would be very grateful for any help.

**Comment by mg262** [comment] 2016-11-22 15:11
Okay, it looks like using leaflet 1.0.0-beta.2 works but Leaflet 1.0.2 doesn't.  I.e. this fixes the problem:

	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.0-beta.2/dist/leaflet.css"/>
	<script src="https://unpkg.com/leaflet@1.0.0-beta.2/dist/leaflet-src.js"></script>
	<script src="https://unpkg.com/leaflet.vectorgrid@latest/dist/Leaflet.VectorGrid.bundled.js"></script>

Worth documenting?

**Comment by IvanSanchez** [comment] 2016-11-22 15:34
Duplicate of #31

**Closed by IvanSanchez** 2016-11-22 15:34 UTC
