### ISSUE TITLE
Some items rendering as circles for MapZen and OpenMapTiles

### ISSUE THREAD

**Issue by akathartos** [Leaflet/Leaflet.VectorGrid#122] opened 2017-09-21 08:42 UTC
It seems that some items are rendering as circles for OpenMapTiles

![image](https://user-images.githubusercontent.com/23725804/30686565-56c7ade0-9ec1-11e7-9495-0587ae6aed71.png)

...and for MapZen:

![image](https://user-images.githubusercontent.com/23725804/30686625-865450d6-9ec1-11e7-8396-d89ae74bf80e.png)

I could't figure out if this was version-specific issue (latest) or related to configuration (copypasted vectorTileStyling from example docs) so any pointers how to fix or remove these circles altogether would be appriciated!

**Comment by perliedman** [comment] 2017-09-21 08:46
Circle markers are the default styling for point geometries, so it's likely you're rendering some point based layer.

**Comment by akathartos** [comment] 2017-09-21 09:20
Thank you for quick reply! Do you have any hints how these could be removed? I tried to look for related attributes from MapZen docs but didn't manage to find anything that I could try with vectorTileStyling definitions.

For MapZen I used the same vectorTileStyling and URL than in the demo so weird thing was that my (latest) environment had these circles appearing but they did not appear in the demo.

**Comment by akathartos** [comment] 2017-09-21 11:28
Items are definitely labels/addresses/text for buildings and water locations. Is there any definition for vectorTileStyling that could be used to hide these altogether?

**Comment by IvanSanchez** [comment] 2017-09-21 11:40
You can use `icon`s (see #44), but unfortunately the ability to instantiate new `L.DivIcon`s (which would fit the user case quite nicely) is not yet implemented.

I'm closing this as a duplicate of https://github.com/Leaflet/Leaflet.VectorGrid/issues/67

**Closed by IvanSanchez** 2017-09-21 11:40 UTC

**Comment by akathartos** [comment] 2017-09-21 12:11
Sorry I didn't make it clear enough that I don't really need the labels, I just wanted to remove those annoying circle markers appearing all around the map.

For anyone else having this issue, reverting to VectorGrid version from latest npm to https://unpkg.com/leaflet.vectorgrid@1.2.0/dist/Leaflet.VectorGrid.bundled.min.js used in demo fixed this issue:

![image](https://user-images.githubusercontent.com/23725804/30694999-16aa19a0-9edf-11e7-8833-ed693cec902b.png)
