### ISSUE TITLE
Click event not working for point geojson featureCollection

### ISSUE THREAD

**Issue by marsmith** [Leaflet/Leaflet.VectorGrid#168] opened 2018-06-13 12:27 UTC
Using version 1.3.0, it seems like there is an issue with events when `interactive: true` is set.  Console is showing "Uncaught TypeError: Cannot read property 'lat' of undefined" on any event (click, mouseover).  I basically just tweaked the demo.

added jsfiddle: https://jsfiddle.net/gfpzvs28/

![image](https://user-images.githubusercontent.com/6529123/41351128-6aa22956-6ee3-11e8-96a0-248574ae5b72.png)

Here is my code:

```
var vectorGrid = L.vectorGrid.slicer( points, { 
	vectorTileLayerStyles: {
		sliced: function(properties, zoom) {

			var state = properties.state_province;
			var radius = 2;
			if (zoom >= 8) radius = 4;
			return {

				fillColor: state === 'Michigan' ? '#800026' :
				state === 'Wisconsin' ? '#E31A1C' :
				state === 'Minnesota' ? '#FEB24C' :
				state === 'New York' ? '#B2FE4C' :
				state === 'Ohio' ? '#B2AE4C' :  
				state === 'Indiana' ? '#A2CE4C' :  
						'#FFEDA0',  //otherwise
				fillOpacity: 0.5,
				opacity: 1,
				stroke: true,
				fill: true,
				weight: 0,
				radius: radius
			}
		}
	},
	interactive: true,
	getFeatureId: function(f) {
		return f.properties.site_id;
	}
})
.on('click', function(e) {
	var properties = e.layer.properties;
	console.log(properties)
})
.addTo(map);
```

**Comment by dowenj** [comment] 2018-06-20 10:57
#148

**Comment by ekeydar** [comment] 2018-06-28 08:34
I've looked on the leaflet code, it seems that the bug is since now Leaflet consider this as marker since it has getLatLng function.

https://github.com/Leaflet/Leaflet/blame/master/src/map/Map.js#L1378

**Comment by chriszrc** [comment] 2018-07-09 18:18
You can read the thread on this issue: https://github.com/Leaflet/Leaflet.VectorGrid/issues/148

There is also a fork you can use with a fix implemented already: https://github.com/chriszrc/Leaflet.VectorGrid

**Comment by karussell** [comment] 2019-06-22 10:29
This problem seems to show up in the unmodified demo too: http://leaflet.github.io/Leaflet.VectorGrid/demo-points.html (with the same error in chromium; in firefox you get several "TypeErrors t is undefined" and "L.DomEvent._fakeStop is not a function" if you click on something)

**Comment by tomchadwin** [comment] 2019-09-24 15:53
Duplicate of #148

**Closed by tomchadwin** 2019-09-24 15:53 UTC
