### ISSUE TITLE
Any workaround for clipped on cell borders

### ISSUE THREAD

**Issue by am2222** [Leaflet/Leaflet.VectorGrid#224] opened 2019-12-19 04:53 UTC
Hi,
I am doing some modifications to be able to load vector tiles from my own data sets. I am fetching a geojson file per each tile and clip it using geojson-vt library and add style to it. everything works fine but there is a problem on edges of the each tile. some cells are not colored by the style. if you look at this image
![SharedScreenshot](https://user-images.githubusercontent.com/4707503/71145925-3ba93000-21f1-11ea-9272-f1487f43c915.jpg)
you can see that there is some problems around each tile. I think this is because they are clipped. and probably they are not known as polygons. is there any way to workaround it? should I add the same background style to each line features as well?

**Comment by tomchadwin** [comment] 2019-12-19 09:43
Can you increase the clip buffer?

**Comment by am2222** [comment] 2019-12-19 18:01
@tomchadwin Thanks, I will try to use buffer to see what happens.

**Comment by am2222** [comment] 2019-12-21 23:04
@tomchadwin Hi, I checked that by decreasing that value it adds more blank hexbins but when I increase it, after a while (I guess 100) it does not make any changes. What do you think? should I clip features manually using a bbox?

**Comment by tomchadwin** [comment] 2020-01-06 11:44
@am2222 Did you set it as high as the full width of a hexbin?

**Comment by am2222** [comment] 2020-01-07 05:58
@tomchadwin Thanks, I guess I found the reason, My query actually did not return some of the hexbins. 
I have another question, Is it possible to add a way to cancel some of the webworkers during the process? lets say we have zoomed into zoom 8 and tiles are loading and we go back to zoom 5 (with this assumption that zoom 5 tiles are not loaded) I think leaflet waits until the previous tiles(in zoom 8) fully loads and then starts to load tiles in zoom 5, which is logical. But Since we changed zoom level I guess the webworkers related to previous zoom levels must get lower priority.

**Comment by tomchadwin** [comment] 2020-01-07 11:41
This is from memory only:

@JamesLMilner did some work on this at the FOSS4GUK 2018 codesprint, and implemented the cancellation of *pending* webworker requests, at the request of @dbauszus-glx (specific ally `fetch` requests, again from memory). He wasn't able to implement the cancellation of requests which had already started, since the API had not been implemented in browsers (possibly the API hadn't even been agreed, in fact).

I guess that the `fetch` cancellation API is now implemented (but I don't know for sure), so this could now be developed.

Anyone have better info than my sketchy memory?

**Comment by IvanSanchez** [comment] 2020-01-07 11:56
> I guess that the fetch cancellation API is now implemented (but I don't know for sure), so this could now be developed.

@tomchadwin You're right about this, see https://caniuse.com/#feat=abortcontroller

Closing this bug because @am2222 found the root cause in their hexbin clipping code. Maybe we should open a new one about cancelling the pending requests when tiles are pruned.

**Closed by IvanSanchez** 2020-01-07 11:56 UTC

**Comment by am2222** [comment] 2020-01-07 16:29
I just added its issue since I guess it will effect rendering performance,
https://github.com/Leaflet/Leaflet.VectorGrid/issues/225
